version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: "Root1234!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
